# Generated by Django 3.2.11 on 2022-02-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default=None, max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
